import Head from 'next/head'
import styles from '../styles/Home.module.css'

function Header() {
  return (     
    <div >
      <Head>
        <title>Supreme</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
    </div>
  );
}

export default Header;